import networkx as nx
import numpy as np
import gymnasium as gym
import specless as sl
from IPython.utils.io import capture_output
from minigrid.core.world_object import fill_coords, point_in_circle
from minigrid.utils.rendering import downsample
from minigrid.core.grid import Grid
from minigrid.core.constants import TILE_PIXELS
from gym_minigrid.minigrid import Grid as GymMinigridGrid

from specless.minigrid.officeenv import OfficeEnv
from specless.utils.conditional_tsp_mapper import ConditionalTSPMapper
from specless.utils.state_regions import StateRegions
from specless.utils.tpo_utils import create_precedence_edges, has_precedence_path
from specless.specification.timed_partial_order import TimedPartialOrder
from specless.specification.conditional_tpo import ConditionalTPO


@classmethod
def _patched_render_tile(cls, obj, agent_dir=None, highlight=False, tile_size=TILE_PIXELS, subdivs=3):
    key = (agent_dir, highlight, tile_size)
    key = obj.encode() + key if obj else key

    if key in cls.tile_cache:
        return cls.tile_cache[key]

    img = np.zeros(shape=(tile_size * subdivs, tile_size * subdivs, 3), dtype=np.uint8)
    fill_coords(img, point_in_circle(0.031, 0.031, 0.031), (100, 100, 100))
    if obj is not None:
        obj.render(img)

    if agent_dir is not None:
        fill_coords(img, point_in_circle(cx=0.5, cy=0.5, r=0.31), (255, 0, 0))

    img = downsample(img, subdivs)
    cls.tile_cache[key] = img
    return img

# Monkey-patch Grid.render_tile to render agent as a circle instead of triangle
# Both minigrid and gym_minigrid have separate Grid classes; patch both since OfficeEnv uses gym_minigrid
_original_render_tile = Grid.render_tile
Grid.render_tile = _patched_render_tile
GymMinigridGrid.render_tile = _patched_render_tile

def create_office_environment(render_mode=None):
    """Create and wrap the Office environment.

    Args:
        render_mode: Rendering mode for the environment (e.g., "rgb_array" for visualization)
    Returns:
        A tuple containing the environment and the transition system.
    """    
    env = gym.make("MiniGrid-Office-v0", render_mode=render_mode, agent_start_pos=(2, 4))
    env = sl.LabelMiniGridWrapper(env, labelkey="color", skiplist=["empty", "wall"])
    env = sl.MiniGridTransitionSystemWrapper(env, ignore_direction=True)

    # Build transition system from environment
    tsbuilder = sl.TSBuilder()
    transition_system = tsbuilder(env)

    print(f" Transition System built:")
    print(f"   States: {len(transition_system.nodes)}")
    print(f"   Edges: {len(transition_system.edges)}")

    return env, transition_system

def define_events_and_mapping(transition_system):
    """
    Define mandatory and optional events, create DTS-TSP mapping.
    
    Args:
        transition_system: The transition system to map.
    Returns:
        A DTS-TSP mapping.
    """

    # Define mandatory events (always required)
    mandatory_events = [
        "initial_state0"  # Starting state (auto-generated by TSPBuilder)
    ]

    # Define optional events (conditionally required)
    optional_events = [
        "floor_blue",    # Puddle - if visited, triggers conditional sequence
        "floor_grey",    # Carpet - required if puddle visited
        "floor_yellow"   # Charger - required if puddle is or isn't visited
    ]

    print(f" Mandatory events: {mandatory_events}")
    print(f" Optional events: {optional_events}")

    # Create Conditional TSP mapping
    mapping = ConditionalTSPMapper(
        transition_system,
        mandatory_events=mandatory_events,
        optional_events=optional_events,
        ignoring_obs_keys=["empty", "wall"]
    )

    mapping.print_summary()

    return mapping

def define_regions(mapping):
    """Define regions over DTS states.

    Args:
        mapping: ConditionalTSPMapper to lookup states by observation
    Returns:
        A StateRegions object.
    """
    regions = StateRegions()
    present = set(mapping.obs_to_states.keys())

    if "floor_blue" in present:
        regions.add_region_by_observations("puddle_area", ["floor_blue"], mapping)
    if "floor_grey" in present:
        regions.add_region_by_observations("carpet_area", ["floor_grey"], mapping)
    if "floor_yellow" in present:
        regions.add_region_by_observations("charger_area", ["floor_yellow"], mapping)

    regions.print_summary(mapping)
    return regions

def create_conditional_tpos(mapping, regions):
    """Create conditional TPOs for puddle and non-puddle paths.

    Specification (assume time in minutes):
    - Mandatory: Start (0-15 min) - always required
    - cTPO 1 (puddle_area): IF puddle visited - Puddle - Carpet (0-3 min)
    - cTPO 2 (non_puddle_area): IF puddle not visited - Charger (0-10 min)

    This creates a conditional chain:
    - Visit puddle - must visit carpet - must visit charger
    - Skip puddle - can go directly to charger
    """
    # Get node IDs
    start_node = mapping.obs_to_node["initial_state0"]
    puddle_node = mapping.obs_to_node["floor_blue"]
    carpet_node = mapping.obs_to_node["floor_grey"]
    charger_node = mapping.obs_to_node["floor_yellow"]

    # Base TPO: Only start is mandatory (with time window)
    base_tpo = TimedPartialOrder.from_constraints(
        global_constraints={
            start_node: (0, 15)  # Start of the plan must occur within 15 min
        }
    )

    print(" Base TPO (must finish all events with the timing constraints):")
    print(f"   {start_node}(start) - time window [0, 15]")

    ctpo = ConditionalTPO(base_tpo, regions)

    # cTPO 1: IF Puddle area visited → Puddle → Carpet
    print("\n cTPO 1 - 'puddle_area' (IF puddle visited):")
    print(f"    {puddle_node}(floor_blue/Puddle) → {carpet_node}(floor_grey/Carpet) [0, 3]")
    print(f"    {carpet_node}(floor_grey/Carpet) → {charger_node}(floor_yellow/Charger) [0, 10]")

    puddle_tpo = TimedPartialOrder.from_constraints(
        global_constraints={},
        local_constraints={
            (start_node, puddle_node): (0, np.inf),
            (puddle_node, carpet_node): (0, 3),     # Carpet within 3 min after puddle
            (carpet_node, charger_node): (0, 10)    # Charger within 10 min after carpet
        }
    )
    ctpo.add_conditional_tpo("puddle_area", puddle_tpo)

    # cTPO 2: IF Puddle NOT visited → Charger required directly
    print("\n cTPO 2 - 'puddle_area' negated (IF puddle not visited):")
    print(f"    {charger_node}(floor_yellow/Charger) [0, 10]")

    no_puddle_tpo = TimedPartialOrder.from_constraints(
        global_constraints={ 
            charger_node: (0, 10)   # Charger within 10 min
        },
        local_constraints={
            (start_node, charger_node): (0, np.inf)  # Charger can be visited any time after start
        }
    )
    ctpo.add_conditional_tpo("puddle_area", no_puddle_tpo, negate=True)

    filename_base = "base_TPO"
    filename_puddle = "conditional_TPO_puddle"
    filename_no_puddle = "conditional_TPO_no_puddle"

    # Visualization
    with capture_output():
        sl.draw_graph(base_tpo, f"visualization/{filename_base}")
        sl.draw_graph(puddle_tpo, f"visualization/{filename_puddle}")
        sl.draw_graph(no_puddle_tpo, f"visualization/{filename_no_puddle}")

    print(f"\n Saved TPO visualizations to 'visualization/' directory.")

    ctpo.print_summary()

    return ctpo


def build_tpo_and_tsp(mapping, ctpo):
    unified_tpo = ctpo.build_unified_tpo()
    tsp_nodes   = mapping.get_tsp_nodes()

    precedence_edges = create_precedence_edges(tsp_nodes, unified_tpo)

    initial_nodes = [
        n for n in tsp_nodes
        if not any(has_precedence_path(unified_tpo, o, n)#, skip_edges=cond_edges)
                   for o in tsp_nodes if o != n)
    ]
    final_nodes = [
        n for n in tsp_nodes
        if not any(has_precedence_path(unified_tpo, n, o)#, skip_edges=cond_edges)
                   for o in tsp_nodes if o != n)
    ]

    edges = list(precedence_edges)
    for fn in final_nodes:
        for in_ in initial_nodes:
            if fn != in_ and (fn, in_) not in edges:
                edges.append((fn, in_))

    print(f" Unified TPO nodes: {tsp_nodes}")
    print(f" Total edges: {len(edges)}")

    tsp_graph = nx.DiGraph()
    tsp_graph.add_edges_from(edges)
    with capture_output():
        sl.draw_graph(unified_tpo, "visualization/unified_TPO")
        sl.draw_graph(tsp_graph, "visualization/TSP_graph")

    return unified_tpo, ctpo.base_tpo, edges, tsp_nodes


def solve_with_costs(mapping, regions, unified_tpo, base_tpo, edges, tsp_nodes, ctpo, favor_puddle):
    start_node = mapping.obs_to_node["initial_state0"]
    puddle_node = mapping.obs_to_node["floor_blue"]
    carpet_node = mapping.obs_to_node["floor_grey"]
    charger_node = mapping.obs_to_node["floor_yellow"]

    max_node = max(tsp_nodes) + 1
    costs = [[1.0 if i != j else 0.0 for j in range(max_node)] for i in range(max_node)]

    if favor_puddle:
        costs[start_node][puddle_node] = 1.0
        costs[puddle_node][carpet_node] = 1.0
        costs[carpet_node][charger_node] = 1.0
        costs[start_node][charger_node] = 50.0
    else:
        costs[start_node][charger_node] = 1.0
        costs[start_node][puddle_node] = 50.0
        costs[puddle_node][carpet_node] = 50.0
        costs[carpet_node][charger_node] = 50.0

    tsp = sl.TSPWithTPO(tsp_nodes, costs, base_tpo)
    tsp.edges = edges
    tsp.nodesets = [[n] for n in tsp_nodes]

    solver = sl.MILPTSPWithRegionTracking(mapping)
    tours, cost, timestamps = solver.solve(
        tsp,
        ctpo=ctpo,
        num_agent=1,
        init_nodes=[start_node],
        come_back_home=False,
    )

    print(f" Tour:  {tours[0]}")
    print(f" Cost:  {cost:.2f}")
    print(f" Events: {[mapping.node_to_obs[n] for n in tours[0]]}")

    solver.print_visited_regions()

    return solver, tours, cost, timestamps