import gymnasium as gym
import specless as sl
from IPython.utils.io import capture_output

from specless.minigrid.officeenv import OfficeEnv
from specless.utils.conditional_tsp_mapper import ConditionalTSPMapper
from specless.utils.state_regions import StateRegions
from specless.specification.timed_partial_order import TimedPartialOrder
from specless.specification.conditional_tpo import ConditionalTPO

def create_office_environment(render_mode=None):
    """Create and wrap the Office environment.

    Args:
        render_mode: Rendering mode for the environment (e.g., "rgb_array" for visualization)
    Returns:
        A tuple containing the environment and the transition system.
    """    
    env = gym.make("MiniGrid-Office-v0", render_mode=render_mode, agent_start_pos=(2, 4))
    env = sl.LabelMiniGridWrapper(env, labelkey="color", skiplist=["empty", "wall"])
    env = sl.MiniGridTransitionSystemWrapper(env, ignore_direction=True)

    # Build transition system from environment
    tsbuilder = sl.TSBuilder()
    transition_system = tsbuilder(env)

    print(f" Transition System built:")
    print(f"   States: {len(transition_system.nodes)}")
    print(f"   Edges: {len(transition_system.edges)}")

    return env, transition_system

def define_events_and_mapping(transition_system):
    """
    Define mandatory and optional events, create DTS-TSP mapping.
    
    Args:
        transition_system: The transition system to map.
    Returns:
        A DTS-TSP mapping.
    """

    # Define mandatory events (always required)
    mandatory_events = [
        "initial_state0"  # Starting state (auto-generated by TSPBuilder)
    ]

    # Define optional events (conditionally required)
    optional_events = [
        "floor_blue",    # Puddle - if visited, triggers conditional sequence
        "floor_grey",    # Carpet - required if puddle visited
        "floor_yellow"   # Charger - required if puddle is or isn't visited
    ]

    print(f" Mandatory events: {mandatory_events}")
    print(f" Optional events: {optional_events}")

    # Create Conditional TSP mapping
    mapping = ConditionalTSPMapper(
        transition_system,
        mandatory_events=mandatory_events,
        optional_events=optional_events,
        ignoring_obs_keys=["empty", "wall"]
    )

    mapping.print_summary()

    return mapping

def define_regions(mapping):
    """Define regions over DTS states.
    
    Args:
        mapping: ConditionalTSPMapper to lookup states by observation
    Returns:
        A StateRegions object.
    """

    regions = StateRegions()

    # Define regions by observation (all states with this observation)
    regions.add_region_by_observation("puddle_area", "floor_blue", mapping)
    regions.add_region_by_observation("carpet_area", "floor_grey", mapping)
    regions.add_region_by_observation("charger_area", "floor_yellow", mapping)

    regions.print_summary(mapping)

    return regions

def create_conditional_tpos(mapping, regions):
    """Create conditional TPOs for puddle and non-puddle paths.

    Specification (assume time in minutes):
    - Mandatory: Start (0-15 min) - always required
    - cTPO 1 (puddle_area): IF puddle visited - Puddle - Carpet (0-3 min)
    - cTPO 2 (non_puddle_area): IF puddle not visited - Charger (0-10 min)

    This creates a conditional chain:
    - Visit puddle - must visit carpet - must visit charger
    - Skip puddle - can go directly to charger
    """
    # Get node IDs
    start_node = mapping.obs_to_node["initial_state0"]
    puddle_node = mapping.obs_to_node["floor_blue"]
    carpet_node = mapping.obs_to_node["floor_grey"]
    charger_node = mapping.obs_to_node["floor_yellow"]

    # Base TPO: Only start is mandatory (with time window)
    base_tpo = TimedPartialOrder.from_constraints(
        global_constraints={
            start_node: (0, 15)  # Start of the plan must occur within 15 min
        }
    )

    print(" Base TPO (must finish all events with the timing constraints):")
    print(f"   {start_node}(start) - time window [0, 15]")

    ctpo = ConditionalTPO(base_tpo, regions)

    # cTPO 1: IF Puddle area visited → Puddle → Carpet
    print("\n cTPO 1 - 'puddle_area' (IF puddle visited):")
    print(f"    {puddle_node}(floor_blue/Puddle) → {carpet_node}(floor_grey/Carpet) [0, 3]")
    print(f"    {carpet_node}(floor_grey/Carpet) → {charger_node}(floor_yellow/Charger) [0, 10]")

    puddle_tpo = TimedPartialOrder.from_constraints(
        global_constraints={},
        local_constraints={
            (puddle_node, carpet_node): (0, 3),     # Carpet within 3 min after puddle
            (carpet_node, charger_node): (0, 10)    # Charger within 10 min after carpet
        }
    )
    ctpo.add_conditional_tpo("puddle_area", puddle_tpo)

    # cTPO 2: IF Puddle NOT visited → Charger required directly
    print("\n cTPO 2 - 'puddle_area' negated (IF puddle not visited):")
    print(f"    {charger_node}(floor_yellow/Charger) [0, 10]")

    no_puddle_tpo = TimedPartialOrder.from_constraints(
        global_constraints={
            charger_node: (0, 10)   # Charger within 10 min
        },
    )
    ctpo.add_conditional_tpo("puddle_area", no_puddle_tpo, negate=True)

    filename_base = "base_TPO"
    filename_puddle = "conditional_TPO_puddle"
    filename_no_puddle = "conditional_TPO_no_puddle"

    # Visualization
    with capture_output():
        sl.draw_graph(base_tpo, f"visualization/{filename_base}")
        sl.draw_graph(puddle_tpo, f"visualization/{filename_puddle}")
        sl.draw_graph(no_puddle_tpo, f"visualization/{filename_no_puddle}")

    print(f"\n Saved TPO visualizations to 'visualization/' directory.")

    ctpo.print_summary()

    return ctpo