import gymnasium as gym
import specless as sl
from specless.minigrid.officeenv import OfficeEnv
from specless.utils.conditional_tsp_mapper import ConditionalTSPMapper

def create_office_environment(render_mode=None):
    """Create and wrap the Office environment.

    Args:
        render_mode: Rendering mode for the environment (e.g., "rgb_array" for visualization)
    Returns:
        A tuple containing the environment and the transition system.
    """    
    env = gym.make("MiniGrid-Office-v0", render_mode=render_mode, agent_start_pos=(2, 4))
    env = sl.LabelMiniGridWrapper(env, labelkey="color", skiplist=["empty", "wall"])
    env = sl.MiniGridTransitionSystemWrapper(env, ignore_direction=True)

    # Build transition system from environment
    tsbuilder = sl.TSBuilder()
    transition_system = tsbuilder(env)

    print(f" Transition System built:")
    print(f"   States: {len(transition_system.nodes)}")
    print(f"   Edges: {len(transition_system.edges)}")

    return env, transition_system

def define_events_and_mapping(transition_system):
    # """Define mandatory and optional events, create DTS-TSP mapping."""
    """
    Define mandatory and optional events, create DTS-TSP mapping.
    
    Args:
        transition_system: The transition system to map.
    Returns:
        A DTS-TSP mapping.
    """

    # Define mandatory events (always required)
    mandatory_events = [
        "initial_state0"  # Starting state (auto-generated by TSPBuilder)
    ]

    # Define optional events (conditionally required)
    optional_events = [
        "floor_blue",    # Puddle - if visited, triggers conditional sequence
        "floor_grey",    # Carpet - required if puddle visited
        "floor_yellow"   # Charger - required if puddle is or isn't visited
    ]

    print(f" Mandatory events: {mandatory_events}")
    print(f" Optional events: {optional_events}")

    # Create Conditional TSP mapping
    mapping = ConditionalTSPMapper(
        transition_system,
        mandatory_events=mandatory_events,
        optional_events=optional_events,
        ignoring_obs_keys=["empty", "wall"]
    )

    mapping.print_summary()

    return mapping
